/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/onecall": {
    get: {
      responses: {
        /** Weather forecast data */
        200: {
          content: {
            "application/json": components["schemas"]["ForecastResponse"];
          };
        };
        /** Unauthorized */
        401: unknown;
        /** Something failed */
        500: unknown;
      };
    };
  };
}

export interface components {
  schemas: {
    Weather: {
      main: string;
      description: string;
    } & { [key: string]: any };
    Temp: {
      day: number;
      max: number;
      night: number;
      eve: number;
      morn: number;
    } & { [key: string]: any };
    Daily: {
      dt: number;
      sunrise: number;
      sunset: number;
      temp: components["schemas"]["Temp"];
      pressure: { [key: string]: any };
      humidity: number;
      wind_speed: number;
      weather: components["schemas"]["Weather"];
      clouds: number;
      rain: number;
      uvi: number;
    } & { [key: string]: any };
    Current: {
      dt: number;
      sunrise: number;
      sunset: number;
      temp: number;
      feels_like: number;
      pressure: number;
      humidity: number;
      clouds: number;
      visibility: number;
      wind_speed: number;
      weather: components["schemas"]["Weather"][];
    } & { [key: string]: any };
    ForecastResponse: {
      lat: number;
      lon: number;
      timezone: string;
      current?: components["schemas"]["Current"];
      daily?: components["schemas"]["Daily"][];
    } & { [key: string]: any };
  };
}

export interface operations {}
